### PR TITLE
Issue#180: updated gradient to match sling hero banner

### LINKED ISSUE #180: Update blog-hero gradients + image
Sling has changed their gradients and the image in the top banner of the 1st level category pages. See https://www.sling.com/whatson/announcements for a new example.

Task: please update these gradients based on the live site the way they look in Mobile view, because I noticed you can't see the full gradient in wider screens. For example, we should capture the orange and black:
image

Also, the image is only "whats on", so new desktop + mobile images need to be used. See https://main--sling--aemsites.aem.page/whatson/announcements for example where I have updated it already, copy + paste to the others.
blog-hero.css
image

### PR DESCRIPTION
**Pull request by neetunegi**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #180

Test URLs:
- Before: https://main--sling--aemsites.aem.live/whatson/announcements
- After: https://issue180--sling--aemsites.hlx.page/whatson/announcements

Note : my fix is following the different pattern for linear gradient method. it genereted from plug in itself. please let me know if there is concern on that

### CODE REVIEW

**Comment by neetunegi** [comment]
adding colorZilla screen shot for any recommendation on color format 
image

**Comment by helms-charity** [comment]
As I said in the ticket, select your colors from what you see in the mobile view. So your dark color is more like rgb(0 43 61 / 100%).
image

Then, please see the new comment with instructions on the ticket for the rest of the hero banners. https://github.com/aemsites/sling/issues/180#issuecomment-2258098475

**Comment by neetunegi** [comment]
for yellow i have to go with more color points to match sling otherwise it was not at all matching. it was looking very dull compared to sling.

**Review by helms-charity — APPROVED** [review]
It looks good, however can you do 2 things before you merge this?
1. At your line 93 of blog-hero.css, can you add "width: 100%" to this, like so? This fixes the logo size.
`.blog-hero.category > div {
    max-width: 1168px;
    margin: 0 auto;
    width: 100%;
}`

2. You can delete the styles for `.blog-hero.category.purple`, `.blog-hero.category.blue-orange`, `.blog-hero.category.gray`, and `.blog-hero.category.tan`. Per Devin, these colors were off-brand and won't be used again.

**Pull request merged**
