### PR TITLE
Offers new

### LINKED ISSUE #9: [Commerce] Packages
Currently GQL calls to commerce to get back different packages and show it in cards.

Screenshot 2024-05-21 at 2 47 21 PM

### LINKED ISSUE #11: Offers
Looks like Offer details coming from commerce graphql.

Need more info to understand which offers to show the end user.

Screenshot 2024-05-21 at 2 50 17 PM
Screenshot 2024-05-21 at 2 50 28 PM

### PR DESCRIPTION
**Pull request by amol-anand**
- added compare plans functionality to the modal
- styling tweaks still needed (see issue https://github.com/aemsites/sling/issues/175 )
- zip code variant (see issue https://github.com/aemsites/sling/issues/174) needed for the compare plans modal

Fix #9 

Test URLs:
- Before: https://main--sling--aemsites.aem.live/drafts/amol/offers
- After: https://offers-new--sling--aemsites.aem.live/drafts/amol/offers

### CODE REVIEW

**Comment by kmurugulla** [comment]
Thanks @amol-anand . quick observation - on https://main--sling--aemsites.aem.live/drafts/amol/offers  the icons are not rendering.

**Comment by helms-charity** [comment]
> Thanks @amol-anand . quick observation - on https://main--sling--aemsites.aem.live/drafts/amol/offers the icons are not rendering.

I think this is the same CORS policy problem, they only allow-listed .page URLs.
https://main--sling--aemsites.aem.page/drafts/amol/offers -- shows the icons.

**Review by helms-charity — COMMENTED** [review]
At line 240 of plan-offer.js, do you have the modal content for "What's included" that you can link there?

**Review by helms-charity — APPROVED** [review]
Looks good, styles can be handled in another ticket...

**Pull request merged**
