### PR TITLE
[WIP] changing the react lib logic to add each block - experimenting

### LINKED ISSUE #276: all gamefinder blocks not loading on a page
When there are moe than one game finder block on the page , it seems all of them are not loading

https://main--sling--aemsites.aem.page/whatson/sports/general-sports/live-sports-schedules-sling-tv

### PR DESCRIPTION
**Pull request by kmurugulla**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #276

Test URLs:
- Before: https://main--sling--aemsites.aem.live/whatson/sports/general-sports/live-sports-schedules-sling-tv
- After: https://276-gamefinder--sling--aemsites.aem.page/whatson/sports/general-sports/live-sports-schedules-sling-tv

### CODE REVIEW

**Review by helms-charity — COMMENTED** [review]
I'm still seeing the different gamefinders load and unload.

**Comment by kmurugulla** [comment]
I will continue to experiment on this , switched to work in progress

**Comment by kmurugulla** [comment]
@helms-charity - could you please review the PR one more time ?
Changes - 
- Rendering all Game Finders Lazily to improve the performance
- The gamefinder react script will load all gamefinder results on the occurance of first game finder

**Comment by helms-charity** [comment]
Some Mobile notes 
image

**Comment by kmurugulla** [comment]
> Some Mobile notes image

- turning off the game finder header floating (in all media sizes), which is similar to the live site
- letting the result rows take height as "auto" so that they are completely visible

**Review by helms-charity — APPROVED** [review]
Working well for me!

**Pull request merged**
