### PR TITLE
Large card on category pages: only show 1st tag

### LINKED ISSUE #187: "Large card" on category pages: only show 1st tag
Per the sling.com site, the 1st "card" should only show the first tag. 
You can try hiding the rest via CSS, but test to see if CLS occurs as a result. Otherwise, this will have to be addressed in the JS.
Example: https://www.sling.com/whatson/sports/college-basketball
image

Example of our page, where there are currently 3 category tags being delivered on 2 lines
https://main--sling--aemsites.aem.page/whatson/entertainment/documentary-and-news

image

### PR DESCRIPTION
**Pull request by neetunegi**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #187 

Test URLs:
- Before: https://main--sling--aemsites.aem.live/whatson/sports/college-basketball
- After: https://issue187--sling--aemsites.aem.live/whatson/sports/college-basketball

- Before: https://main--sling--aemsites.aem.live/whatson/entertainment/home-and-food
- After: https://issue187--sling--aemsites.aem.live/whatson/entertainment/home-and-food

- Before: https://main--sling--aemsites.aem.live/whatson/entertainment/documentary-and-news
- After: https://issue187--sling--aemsites.aem.live/whatson/entertainment/documentary-and-news

### CODE REVIEW

**Review by helms-charity — COMMENTED** [review]
When the tag has '&' in it, such as "Documentary & News" or "Home & Food", no tag is showing in the Large Card. See these pages:
https://issue187--sling--aemsites.aem.live/whatson/entertainment/documentary-and-news
https://issue187--sling--aemsites.aem.live/whatson/entertainment/home-and-food

**Comment by neetunegi** [comment]
i will look into this.

**Comment by neetunegi** [comment]
please check

**Review by helms-charity — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
